-- dbo.ReporteProductividadSecondsView source

CREATE view [dbo].[ReporteProductividadSecondsView]
as
SELECT [ServidorOrigen]
      ,[server_ip]
      ,[event_date]
      ,[user_id]
      ,[full_name]
      ,[campaign_id]
      ,[user_group]
      ,[timeclock]
	  ,dbo.fn_Time_to_sec([timeclock]) as [timeclock_sec] 
      , dbo.fn_Sec_to_Time( dbo.fn_Time_to_sec([talk]) + dbo.fn_Time_to_sec([wait]) +dbo.fn_Time_to_sec([dispo]) +dbo.fn_Time_to_sec([pause]))  as [agenttime]
	  ,dbo.fn_Time_to_sec([talk]) + dbo.fn_Time_to_sec([wait]) +dbo.fn_Time_to_sec([dispo]) +dbo.fn_Time_to_sec([pause])   as [agenttime_sec] 
      ,[talk]
	  ,dbo.fn_Time_to_sec([talk]) as [talk_sec]
      ,[costumer]
	  ,dbo.fn_Time_to_sec([costumer]) as [costumer_sec]
      ,[dead] 
	  ,dbo.fn_Time_to_sec([dead]) as [dead_sec]
      ,[wait]
	  ,dbo.fn_Time_to_sec([wait]) as [wait_sec]
      ,[dispo]
	  ,dbo.fn_Time_to_sec([dispo]) as [dispo_sec]
      ,[pause]
	  ,dbo.fn_Time_to_sec([pause]) as [pause_sec]
      ,[andial]
	  ,dbo.fn_Time_to_sec([andial]) as [andial_sec]
      ,[ba]
	  ,dbo.fn_Time_to_sec([ba]) as [ba_sec]
      ,[brk]
	  ,dbo.fn_Time_to_sec([brk]) as [brk_sec]
      ,[caling]
	  ,dbo.fn_Time_to_sec([caling]) as [caling_sec]
      ,[jun]
	  ,dbo.fn_Time_to_sec([jun]) as [jun_sec]
      ,[lagged]
	  ,dbo.fn_Time_to_sec([lagged]) as [lagged_sec]
      ,[login]
	  ,dbo.fn_Time_to_sec([login]) as [login_sec]
      ,[nxdial]
	  ,dbo.fn_Time_to_sec([nxdial]) as [nvdial_sec]
      ,[rea]
	  ,dbo.fn_Time_to_sec([rea]) as [rea_sec]
      ,[retro]
	  ,dbo.fn_Time_to_sec([retro]) as [retro_sec]
      ,[noncode]
	  ,dbo.fn_Time_to_sec([noncode]) as [noncode_sec]
      ,[CALLS]
      ,[A]
      ,[A1L]
      ,[A1V]
      ,[A4S]
      ,[ADC]
      ,[ALTNUM]
      ,[B2A]
      ,[B2H]
      ,[B2R]
      ,[B4H]
      ,[B8U]
      ,[C1P]
      ,[C4H]
      ,[C7F]
      ,[C7P]
      ,[C7R]
      ,[C8N]
      ,[D2W]
      ,[D6B]
      ,[DNCL]
      ,[DONEM]
      ,[E1B]
      ,[E2E]
      ,[E2L]
      ,[E3L]
      ,[E3X]
      ,[E7B]
      ,[E7U]
      ,[E9P]
      ,[ERI]
      ,[F2X]
      ,[F9H]
      ,[G3U]
      ,[G8K]
      ,[H4C]
      ,[H8Q]
      ,[I1E]
      ,[I1M]
      ,[I1O]
      ,[I4I]
      ,[I6A]
      ,[I6X]
      ,[I9H]
      ,[I9I]
      ,[J3D]
      ,[J4A]
      ,[J5Q]
      ,[J6T]
      ,[J8K]
      ,[K3B]
      ,[K9B]
      ,[K9L]
      ,[L2F]
      ,[L4M]
      ,[L5I]
      ,[L9P]
      ,[M1G]
      ,[M4U]
      ,[M4W]
      ,[M7D]
      ,[N]
      ,[N3F]
      ,[N4I]
      ,[N6T]
      ,[N7J]
      ,[N8B]
      ,[O2E]
      ,[O4X]
      ,[O5F]
      ,[P5I]
      ,[P6S]
      ,[P7T]
      ,[P8P]
      ,[PU]
      ,[Q1F]
      ,[Q5I]
      ,[Q5M]
      ,[Q6W]
      ,[Q8J]
      ,[R5H]
      ,[S2W]
      ,[S3L]
      ,[T8J]
      ,[U1K]
      ,[U2F]
      ,[U3M]
      ,[U3Z]
      ,[U5X]
      ,[U8A]
      ,[U9U]
      ,[V2U]
      ,[V5N]
      ,[V5T]
      ,[V6O]
      ,[W5N]
      ,[W6D]
      ,[W6W]
      ,[W9L]
      ,[W9Q]
      ,[X1C]
      ,[X1R]
      ,[X6G]
      ,[X6V]
      ,[X8Y]
      ,[X9R]
      ,[Y3R]
      ,[Y4B]
      ,[Y4U]
      ,[Y6J]
      ,[Z6B]
      ,[Z6H]
      ,[NA]
	  , dbo.fn_Time_to_sec([talk]) + dbo.fn_Time_to_sec([wait]) +dbo.fn_Time_to_sec([dispo]) as [efectivetime_sec] 
  FROM DWH.Logs.dbo.ReporteProductividad;