DROP TABLE IF EXISTS `%name_strtolower%`;
CREATE TABLE `%name_strtolower%` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `vCampo1_%name_strtolower%` varchar(200) NULL DEFAULT NULL,
  `vCampo2_%name_strtolower%` varchar(210) NULL DEFAULT NULL,
  `vCampo3_%name_strtolower%` varchar(220) NULL DEFAULT NULL,
  `vCampo4_%name_strtolower%` varchar(230) NULL DEFAULT NULL,
  `vCampo5_%name_strtolower%` varchar(240) NULL DEFAULT NULL,
  `vCampo6_%name_strtolower%` varchar(250) NULL DEFAULT NULL,
  `vCampo7_%name_strtolower%` varchar(260) NULL DEFAULT NULL,
  `vCampo8_%name_strtolower%` varchar(270) NULL DEFAULT NULL,
  `vCampo9_%name_strtolower%` varchar(280) NULL DEFAULT NULL,
  `vCampo10_%name_strtolower%` varchar(290) NULL DEFAULT NULL,
  `vCampo11_%name_strtolower%` varchar(300) NULL DEFAULT NULL,
  `vCampo12_%name_strtolower%` varchar(310) NULL DEFAULT NULL,
  `vCampo13_%name_strtolower%` varchar(320) NULL DEFAULT NULL,
  `vCampo14_%name_strtolower%` varchar(340) NULL DEFAULT NULL,
  `vCampo15_%name_strtolower%` varchar(350) NULL DEFAULT NULL,
  `vCampo16_%name_strtolower%` varchar(360) NULL DEFAULT NULL,
  `vCampo17_%name_strtolower%` varchar(370) NULL DEFAULT NULL,
  `vCampo18_%name_strtolower%` varchar(380) NULL DEFAULT NULL,
  `vCampo19_%name_strtolower%` varchar(390) NULL DEFAULT NULL,
  `vCampo20_%name_strtolower%` varchar(400) NULL DEFAULT NULL,
  `vCampo21_%name_strtolower%` varchar(410) NULL DEFAULT NULL,
  `vCampo22_%name_strtolower%` varchar(420) NULL DEFAULT NULL,
  `vCampo23_%name_strtolower%` varchar(430) NULL DEFAULT NULL,
  `vCampo24_%name_strtolower%` varchar(440) NULL DEFAULT NULL,
  `vCampo25_%name_strtolower%` varchar(450) NULL DEFAULT NULL,
  `vCampo26_%name_strtolower%` varchar(460) NULL DEFAULT NULL,
  `vCampo27_%name_strtolower%` varchar(470) NULL DEFAULT NULL,
  `vCampo28_%name_strtolower%` varchar(480) NULL DEFAULT NULL,
  `vCampo29_%name_strtolower%` varchar(490) NULL DEFAULT NULL,
  `vCampo30_%name_strtolower%` varchar(500) NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `b_status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

