DROP TABLE IF EXISTS `probando`;
CREATE TABLE `probando` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `vCampo1_probando` varchar(200) NULL DEFAULT NULL,
  `vCampo2_probando` varchar(210) NULL DEFAULT NULL,
  `vCampo3_probando` varchar(220) NULL DEFAULT NULL,
  `vCampo4_probando` varchar(230) NULL DEFAULT NULL,
  `vCampo5_probando` varchar(240) NULL DEFAULT NULL,
  `vCampo6_probando` varchar(250) NULL DEFAULT NULL,
  `vCampo7_probando` varchar(260) NULL DEFAULT NULL,
  `vCampo8_probando` varchar(270) NULL DEFAULT NULL,
  `vCampo9_probando` varchar(280) NULL DEFAULT NULL,
  `vCampo10_probando` varchar(290) NULL DEFAULT NULL,
  `vCampo11_probando` varchar(300) NULL DEFAULT NULL,
  `vCampo12_probando` varchar(310) NULL DEFAULT NULL,
  `vCampo13_probando` varchar(320) NULL DEFAULT NULL,
  `vCampo14_probando` varchar(340) NULL DEFAULT NULL,
  `vCampo15_probando` varchar(350) NULL DEFAULT NULL,
  `vCampo16_probando` varchar(360) NULL DEFAULT NULL,
  `vCampo17_probando` varchar(370) NULL DEFAULT NULL,
  `vCampo18_probando` varchar(380) NULL DEFAULT NULL,
  `vCampo19_probando` varchar(390) NULL DEFAULT NULL,
  `vCampo20_probando` varchar(400) NULL DEFAULT NULL,
  `vCampo21_probando` varchar(410) NULL DEFAULT NULL,
  `vCampo22_probando` varchar(420) NULL DEFAULT NULL,
  `vCampo23_probando` varchar(430) NULL DEFAULT NULL,
  `vCampo24_probando` varchar(440) NULL DEFAULT NULL,
  `vCampo25_probando` varchar(450) NULL DEFAULT NULL,
  `vCampo26_probando` varchar(460) NULL DEFAULT NULL,
  `vCampo27_probando` varchar(470) NULL DEFAULT NULL,
  `vCampo28_probando` varchar(480) NULL DEFAULT NULL,
  `vCampo29_probando` varchar(490) NULL DEFAULT NULL,
  `vCampo30_probando` varchar(500) NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `b_status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

